#!/bin/sh
. ./Common

###############################################################################

ptest "codegen: global wave_a = 1" -c -q <<EOF
wave_a = 1
EOF
expect <<EOF
EOF

#------------------------------------------------------------------------------

ptest_fail "codegen: global foo = 1" -c -q <<EOF
foo = 1
EOF
expect <<EOF
FPVM, line 2: can initialize non-system variables only to zero near 'EOF'
EOF

#------------------------------------------------------------------------------

ptest_fail "codegen: wave_a = bar" -c -q <<EOF
wave_a = bar
EOF
expect <<EOF
FPVM, line 2: value must be a constant near 'EOF'
EOF

###############################################################################
