#!/bin/sh
#
# Common - Elements shared by all regression tests for the FNP parser
#
# Written 2010, 2011 by Werner Almesberger
# Copyright 2010, 2011 Werner Almesberger
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#


ptest()
{
	echo -n "$1: " 1>&2
	shift
	$VALGRIND ${PTST:-../ptest/ptest} "$@" >_out 2>&1 || {
		echo FAILED "($SCRIPT)" 1>&2
		cat _out
		rm -f _out
		exit 1
	}
}


ptest_fail()
{
	echo -n "$1: " 1>&2
	shift
	$VALGRIND ${PTST:-../ptest/ptest} "$@" >_out 2>&1 && {
		echo FAILED "($SCRIPT)" 1>&2
		cat _out
		rm -f _out
		exit 1
	}
}


expect()
{
	diff -u - "$@" _out >_diff || {
		echo FAILED "($SCRIPT)" 1>&2
		cat _diff 1>&2
		rm -f _out _diff
		exit 1
	}
	echo PASSED 1>&2
	rm -f _out _diff
	passed=`expr ${passed:-0} + 1`
}
