#!/bin/sh
. ./Common

###############################################################################

ptest "comment: line with just // " <<EOF
// this is a comment
sx = b + c
EOF
expect <<EOF
sx = (+ b c)
EOF

#------------------------------------------------------------------------------

ptest "comment: line ending with // comment" <<EOF
sx = b + c // comment
sy = e + f
EOF
expect <<EOF
sx = (+ b c)
sy = (+ e f)
EOF

#------------------------------------------------------------------------------

ptest "comment: // after //" <<EOF
sx = b + c // comment // more
sy = e + f
EOF
expect <<EOF
sx = (+ b c)
sy = (+ e f)
EOF

#------------------------------------------------------------------------------

ptest "comment: // ending with EOF" "sx = b// end"
expect <<EOF
sx = b
EOF

#------------------------------------------------------------------------------

ptest "comment: /* ... */" <<EOF
sx = b + c /* comment */
sy = e + f
EOF
expect <<EOF
sx = (+ b c)
sy = (+ e f)
EOF

#------------------------------------------------------------------------------

ptest "comment: /* ... newline ... */" <<EOF
sx = b + c /* comment
more */ sy = e + f
EOF
expect <<EOF
sx = (+ b c)
sy = (+ e f)
EOF

#------------------------------------------------------------------------------

ptest "comment: /* ... * ... */" <<EOF
sx = 1 /* comment * more */
sy = 2
EOF
expect <<EOF
sx = 1
sy = 2
EOF

#------------------------------------------------------------------------------

ptest "comment: /* ... ** ... */" <<EOF
sx = 3 /* comment ** more */
sy = 4
EOF
expect <<EOF
sx = 3
sy = 4
EOF

#------------------------------------------------------------------------------

ptest "comment: /* ... **/" <<EOF
sx = 5 /* comment **/
sy = 6
EOF
expect <<EOF
sx = 5
sy = 6
EOF

#------------------------------------------------------------------------------

ptest "comment: /**/" <<EOF
sx = 7 /**/
sy = 8
EOF
expect <<EOF
sx = 7
sy = 8
EOF

#------------------------------------------------------------------------------

ptest_fail "comment: /*/ (error)" <<EOF
sx = 9 /*/
sy = a
EOF
expect <<EOF
line 1: parse error near '*/'
EOF

#------------------------------------------------------------------------------

ptest_fail "comment: unterminated /* ... with newline" <<EOF
sx = b + c /* comment
sy = e + f
EOF
expect <<EOF
line 1: parse error near '*'
EOF

#------------------------------------------------------------------------------

ptest_fail "comment: unterminated /* ... without newline" "a = b+c /* comment"
expect <<EOF
line 1: parse error near '*'
EOF

#------------------------------------------------------------------------------

ptest "comment: multiple /*...*/ comments" <<EOF
/* */ sx /* */
/***/ =  /**/
/**/  b /* */
EOF
expect <<EOF
sx = b
EOF

#------------------------------------------------------------------------------

ptest "comment: [preset00]" <<EOF
  [preset00]
sx=y
EOF
expect <<EOF
sx = y
EOF

###############################################################################
