#!/bin/sh
. ./Common

###############################################################################

ptest "conditional: x = a ? b : c" <<EOF
x = a ? b : c
EOF
expect <<EOF
x = (if a b c)
EOF

#------------------------------------------------------------------------------

ptest "conditional: x = a+b ? c+d : e+f" <<EOF
x = a+b ? c+d : e+f
EOF
expect <<EOF
x = (if (+ a b) (+ c d) (+ e f))
EOF

#------------------------------------------------------------------------------

ptest "conditional: x = a ? b ? c : d : e" <<EOF
x = a ? b ? c : d : e
EOF
expect <<EOF
x = (if a (if b c d) e)
EOF

#------------------------------------------------------------------------------

ptest "conditional: x = a ? b : c ? d : e" <<EOF
x = a ? b : c ? d : e
EOF
expect <<EOF
x = (if a b (if c d e))
EOF

###############################################################################
