#!/bin/sh
. ./Common

###############################################################################

ptest "conditional: sx = a ? b : c" <<EOF
sx = a ? b : c
EOF
expect <<EOF
sx = (if a b c)
EOF

#------------------------------------------------------------------------------

ptest "conditional: sx = a+b ? c+d : e+f" <<EOF
sx = a+b ? c+d : e+f
EOF
expect <<EOF
sx = (if (+ a b) (+ c d) (+ e f))
EOF

#------------------------------------------------------------------------------

ptest "conditional: sx = a ? b ? c : d : e" <<EOF
sx = a ? b ? c : d : e
EOF
expect <<EOF
sx = (if a (if b c d) e)
EOF

#------------------------------------------------------------------------------

ptest "conditional: sx = a ? b : c ? d : e" <<EOF
sx = a ? b : c ? d : e
EOF
expect <<EOF
sx = (if a b (if c d e))
EOF

###############################################################################
