#!/bin/sh
. ./Common

###############################################################################

ptest "dual use: min = sin+cos" <<EOF
per_frame:
min = sin+cos
EOF
expect <<EOF
per_frame = min = (+ (sin) (cos))
EOF

#------------------------------------------------------------------------------

ptest "dual use: sin = sqr-if" <<EOF
per_frame=
sin = sqr-if
EOF
expect <<EOF
per_frame = sin = (- (sqr) (if))
EOF

#------------------------------------------------------------------------------

ptest "dual use: if = max*int (old style)" <<EOF
per_frame=
if = max*int
EOF
expect <<EOF
per_frame = if = (* (max) (int))
EOF

#------------------------------------------------------------------------------

ptest_fail "dual use: if = max*int (new style)" <<EOF
per_frame:
dummy = 0	/* scanner switches one token after section */
if = max*int
EOF
expect <<EOF
line 3: parse error near '='
EOF

###############################################################################
