#!/bin/sh
. ./Common

###############################################################################

ptest "dual use: min = sin+cos" <<EOF
per_frame:
min = sin+cos
EOF
expect <<EOF
per_frame = min = (+ (sin) (cos))
EOF

#------------------------------------------------------------------------------

ptest "dual use: sin = sqr-max" <<EOF
per_frame=
sin = sqr-max
EOF
expect <<EOF
per_frame = sin = (- (sqr) (max))
EOF

#------------------------------------------------------------------------------

ptest "dual use: bnot = max*int" <<EOF
per_frame=
bnot = max*int
EOF
expect <<EOF
per_frame = bnot = (* (max) (int))
EOF

#------------------------------------------------------------------------------

ptest_fail "dual use: if = max*int (forbidden)" <<EOF
per_frame:
if = max*int
EOF
expect <<EOF
line 2: parse error near 'if'
EOF

###############################################################################
