#!/bin/sh
. ./Common

###############################################################################

ptest "equation numbers: old-style per_frame" <<EOF
per_frame_0 = foo = 1
EOF
expect <<EOF
per_frame = foo = 1
EOF

#------------------------------------------------------------------------------

ptest "equation numbers: old-style per_vertex" <<EOF
per_vertex_20 = foo = 2
EOF
expect <<EOF
per_vertex = foo = 2
EOF

#------------------------------------------------------------------------------

ptest "equation numbers: old-style per_pixel" <<EOF
per_pixel_n0 = foo = 3
EOF
expect <<EOF
per_vertex = foo = 3
EOF

#------------------------------------------------------------------------------

ptest_fail "equation numbers: new-style per_frame" <<EOF
per_frame_0:
	foo = 1
EOF
expect <<EOF
line 1: parse error near ':'
EOF

#------------------------------------------------------------------------------

ptest_fail "equation numbers: new-style per_vertex" <<EOF
per_vertex_2:
	foo = 2
EOF
expect <<EOF
line 1: parse error near ':'
EOF

###############################################################################
