#!/bin/sh
. ./Common

###############################################################################

ptest_fail "syntax error: x = backtick" <<EOF
x = \`
EOF
expect <<EOF
FPVM, line 1: scan error near '\`'
EOF

#------------------------------------------------------------------------------

ptest_fail "syntax error: x = a b" <<EOF
x = a b
EOF
expect <<EOF
x = a
FPVM, line 2: parse error near 'EOF'
EOF

#------------------------------------------------------------------------------

ptest_fail "syntax error: x = a + + b" <<EOF
x = a + + b
EOF
expect <<EOF
FPVM, line 1: parse error near '+'
EOF

#------------------------------------------------------------------------------

ptest_fail "code generation error" -f "codegen" <<EOF
x = a + b
EOF
expect <<EOF
FPVM, line 2: codegen near 'EOF'
EOF

###############################################################################
