#!/bin/sh
. ./Common

###############################################################################

ptest_fail "syntax error: x = backtick" <<EOF
x = \`
EOF
expect <<EOF
FPVM, line 1, near "\`": scan error
EOF

#------------------------------------------------------------------------------

ptest_fail "syntax error: x = a b" <<EOF
x = a b
EOF
expect <<EOF
x = a
FPVM, line 1, near "b": parse error
EOF

#------------------------------------------------------------------------------

ptest_fail "syntax error: x = a + + b" <<EOF
x = a + + b
EOF
expect <<EOF
FPVM, line 1, near "+": parse error
EOF

###############################################################################
