#!/bin/sh
. ./Common

###############################################################################

ptest "fold conditional: sx = a ? b : c (nothing to fold)" << EOF
sx = a ? b : c
EOF
expect <<EOF
sx = (if a b c)
EOF

#------------------------------------------------------------------------------

ptest "fold conditional: sx = 1 ? b : c" << EOF
sx = 1 ? b : c
EOF
expect <<EOF
sx = b
EOF

#------------------------------------------------------------------------------

ptest "fold conditional: sx = 0 ? b : c" << EOF
sx = 0 ? b : c
EOF
expect <<EOF
sx = c
EOF

#------------------------------------------------------------------------------

ptest "fold conditional: sx = if(a, b, c) (nothing to fold)" << EOF
sx = if(a, b, c)
EOF
expect <<EOF
sx = (if a b c)
EOF

#------------------------------------------------------------------------------

ptest "fold conditional: sx = if(1, b, c)" << EOF
sx = if(1, b, c)
EOF
expect <<EOF
sx = b
EOF

#------------------------------------------------------------------------------

ptest "fold conditional: sx = if(0, b,c)" << EOF
sx = if(0, b, c)
EOF
expect <<EOF
sx = c
EOF

###############################################################################
