#!/bin/sh
. ./Common

###############################################################################

ptest "constant folding: x = 1+2" << EOF
x = 1+2
EOF
expect <<EOF
x = 3
EOF

#------------------------------------------------------------------------------

ptest "constant folding: x = 1-2" << EOF
x = 1-2
EOF
expect <<EOF
x = -1
EOF

#------------------------------------------------------------------------------

ptest "constant folding: x = 2*3" << EOF
x = 2*3
EOF
expect <<EOF
x = 6
EOF

#------------------------------------------------------------------------------

ptest "constant folding: x = 4/5" << EOF
x = 4/5
EOF
expect <<EOF
x = 0.8
EOF

#------------------------------------------------------------------------------

ptest "constant folding: x = 2.8 % 0.5" << EOF
x = 2.8 % 0.5
EOF
expect <<EOF
x = 0.3
EOF

#------------------------------------------------------------------------------

ptest "constant folding: x = a+1 (nothign to fold)" << EOF
x = a+1
EOF
expect <<EOF
x = (+ a 1)
EOF

#------------------------------------------------------------------------------

ptest "constant folding: x = 1+b (nothign to fold)" << EOF
x = 1+b
EOF
expect <<EOF
x = (+ 1 b)
EOF

#------------------------------------------------------------------------------

ptest "constant folding: above" << EOF
x = above(1, 2)
y = above(2, 1)
z = above(1, 1)
EOF
expect <<EOF
x = 0
y = 1
z = 0
EOF

#------------------------------------------------------------------------------

ptest "constant folding: below" << EOF
x = below(1, 2)
y = below(2, 1)
z = below(1, 1)
EOF
expect <<EOF
x = 1
y = 0
z = 0
EOF

#------------------------------------------------------------------------------

ptest "constant folding: equal" << EOF
x = equal(1, 2)
y = equal(2, 1)
z = equal(1, 1)
EOF
expect <<EOF
x = 0
y = 0
z = 1
EOF

#------------------------------------------------------------------------------

ptest "constant folding: max" << EOF
x = max(2, 3)
y = max(3, 2)
EOF
expect <<EOF
x = 3
y = 3
EOF

#------------------------------------------------------------------------------

ptest "constant folding: min" << EOF
x = min(2, 3)
y = min(3, 2)
EOF
expect <<EOF
x = 2
y = 2
EOF

###############################################################################
