#!/bin/sh
. ./Common

###############################################################################

ptest "constant folding: sx = 1+2" << EOF
sx = 1+2
EOF
expect <<EOF
sx = 3
EOF

#------------------------------------------------------------------------------

ptest "constant folding: sx = 1-2" << EOF
sx = 1-2
EOF
expect <<EOF
sx = -1
EOF

#------------------------------------------------------------------------------

ptest "constant folding: sx = 2*3" << EOF
sx = 2*3
EOF
expect <<EOF
sx = 6
EOF

#------------------------------------------------------------------------------

ptest "constant folding: sx = 4/5" << EOF
sx = 4/5
EOF
expect <<EOF
sx = 0.8
EOF

#------------------------------------------------------------------------------

ptest "constant folding: sx = 2.8 % 0.5" << EOF
sx = 2.8 % 0.5
EOF
expect <<EOF
sx = 0.3
EOF

#------------------------------------------------------------------------------

ptest "constant folding: sx = a+1 (nothing to fold)" << EOF
sx = a+1
EOF
expect <<EOF
sx = (+ a 1)
EOF

#------------------------------------------------------------------------------

ptest "constant folding: sx = 1+b (nothing to fold)" << EOF
sx = 1+b
EOF
expect <<EOF
sx = (+ 1 b)
EOF

#------------------------------------------------------------------------------

ptest "constant folding: above" << EOF
sx = above(1, 2)
sy = above(2, 1)
cx = above(1, 1)
EOF
expect <<EOF
sx = 0
sy = 1
cx = 0
EOF

#------------------------------------------------------------------------------

ptest "constant folding: below" << EOF
sx = below(1, 2)
sy = below(2, 1)
cx = below(1, 1)
EOF
expect <<EOF
sx = 1
sy = 0
cx = 0
EOF

#------------------------------------------------------------------------------

ptest "constant folding: equal" << EOF
sx = equal(1, 2)
sy = equal(2, 1)
cx = equal(1, 1)
EOF
expect <<EOF
sx = 0
sy = 0
cx = 1
EOF

#------------------------------------------------------------------------------

ptest "constant folding: max" << EOF
sx = max(2, 3)
sy = max(3, 2)
EOF
expect <<EOF
sx = 3
sy = 3
EOF

#------------------------------------------------------------------------------

ptest "constant folding: min" << EOF
sx = min(2, 3)
sy = min(3, 2)
EOF
expect <<EOF
sx = 2
sy = 2
EOF

#------------------------------------------------------------------------------

ptest "constant folding: unary minus" << EOF
sx = -2
EOF
expect <<EOF
sx = -2
EOF

#------------------------------------------------------------------------------

ptest "constant folding: sqr" << EOF
sx = sqr(3)
EOF
expect <<EOF
sx = 9
EOF

#------------------------------------------------------------------------------

ptest "constant folding: sqrt" << EOF
sx = sqrt(2.25)
EOF
expect <<EOF
sx = 1.5
EOF

###############################################################################
