#!/bin/sh
. ./Common

# WORK IN PROGRESS

###############################################################################

ptest "image: imagefile1=hello" <<EOF
imagefile1=hello
EOF
expect <<EOF
image 1 = "hello"
EOF

#------------------------------------------------------------------------------

ptest "image: imagefile2 = hello" <<EOF
imagefile2 = hello
EOF
expect <<EOF
image 2 = "hello"
EOF

#------------------------------------------------------------------------------

ptest "image: imagefile1 = hel lo" <<EOF
imagefile1 = hel lo
EOF
expect <<EOF
image 1 = "hel lo"
EOF

#------------------------------------------------------------------------------

ptest "image: imagefile2 = hel<nl>sx" <<EOF
imagefile2 = hel
sx = u
EOF
expect <<EOF
image 2 = "hel"
sx = u
EOF

#------------------------------------------------------------------------------

ptest "image: imagefile1 = foo<spc><spc>" "imagefile1 = foo  "
expect <<EOF
image 1 = "foo"
EOF

#------------------------------------------------------------------------------

ptest "image: imagefile2 = /dev/null" <<EOF
imagefile2 = /dev/null
EOF
expect <<EOF
image 2 = "/dev/null"
EOF

#------------------------------------------------------------------------------

ptest "image: imagefile1 = *** test  -  robust & ness ***" <<EOF
imagefile1 = *** test  -  robust & ness ***
EOF
expect <<EOF
image 1 = "*** test  -  robust & ness ***"
EOF

#------------------------------------------------------------------------------

ptest_fail "image: imagefile0=foo" -c <<EOF
imagefile0=foo
EOF
expect <<EOF
line 2: can initialize non-system variables only to zero near 'EOF'
EOF

#------------------------------------------------------------------------------

ptest_fail "image: imagefile3=foo" -c <<EOF
imagefile3=foo
EOF
expect <<EOF
line 2: image number out of bounds near 'EOF'
EOF

###############################################################################
