#!/bin/sh
. ./Common

###############################################################################

ptest "initial: initialize non-system to zero" <<EOF
foo = 0
EOF
expect <<EOF
EOF

#------------------------------------------------------------------------------

ptest "initial: initialize per-frame to non-zero" <<EOF
wave_x = 1
EOF
expect <<EOF
wave_x = 1
EOF

#------------------------------------------------------------------------------

ptest_fail "initial: initialize per-vertex to non-zero" <<EOF
_texsize = 1
EOF
expect <<EOF
FPVM, line 2: can initialize non-system variables only to zero near 'EOF'
EOF

#------------------------------------------------------------------------------

ptest_fail "initial: initialize non-system to non-zero" <<EOF
foo = 1
EOF
expect <<EOF
FPVM, line 2: can initialize non-system variables only to zero near 'EOF'
EOF

#------------------------------------------------------------------------------

ptest_fail "initial: initialize non-system to non-number" <<EOF
foo = bar
EOF
expect <<EOF
FPVM, line 2: can initialize non-system variables only to zero near 'EOF'
EOF

###############################################################################
