#!/bin/sh
. ./Common

###############################################################################

ptest_fail "location: scanner, inside line" <<EOF
rot = b
x = \` y
c = d
EOF
expect <<EOF
rot = b
FPVM, line 2: scan error near '\`'
EOF

#------------------------------------------------------------------------------

ptest_fail "location: scanner, beginning of line" <<EOF
a = b
\`x = y
c = d
EOF
expect <<EOF
FPVM, line 2: scan error near '\`'
EOF

#------------------------------------------------------------------------------

ptest_fail "location: scanner, end of line" <<EOF
sx = b
x = y\`
c = d
EOF
expect <<EOF
sx = b
FPVM, line 2: scan error near '\`'
EOF

#------------------------------------------------------------------------------

ptest_fail "location: parser, inside line" <<EOF
sx = b
x = * y
c = d
EOF
expect <<EOF
sx = b
FPVM, line 2: parse error near '*'
EOF

#------------------------------------------------------------------------------

ptest_fail "location: parser, beginning of line" <<EOF
sx = b
)x = y
c = d
EOF
expect <<EOF
sx = b
FPVM, line 2: parse error near ')x'
EOF

#------------------------------------------------------------------------------

ptest_fail "location: parser, end of line (1)" <<EOF
sx = b
sy = y(
c = d
EOF
expect <<EOF
sx = b
sy = y
FPVM, line 2: parse error near '('
EOF

#------------------------------------------------------------------------------

ptest_fail "location: parser, end of line (2)" <<EOF
sx = b
x = )
c = d
EOF
expect <<EOF
sx = b
FPVM, line 2: parse error near ')'
EOF

#------------------------------------------------------------------------------

ptest_fail "location: error is end of line" <<EOF
sx = b
x =
EOF
expect <<EOF
sx = b
FPVM, line 3: parse error near 'EOF'
EOF

#------------------------------------------------------------------------------

ptest_fail "location: error is EOF" "x="
expect <<EOF
FPVM, line 1: parse error near 'EOF'
EOF

#------------------------------------------------------------------------------

ptest_fail "location: error is identifier" <<EOF
sx = this is an error
EOF
expect <<EOF
sx = this
FPVM, line 1: parse error near 'an'
EOF

#------------------------------------------------------------------------------

ptest_fail "location: 3rd line" <<EOF
sx = b
sy = d
)
EOF
expect <<EOF
sx = b
sy = d
FPVM, line 3: parse error near ')'
EOF

#------------------------------------------------------------------------------

ptest_fail "location: 5th line, with // comments" <<EOF
// assign a
sx = b
// assign c
sy = d
)
EOF
expect <<EOF
sx = b
sy = d
FPVM, line 5: parse error near ')'
EOF

#------------------------------------------------------------------------------

ptest_fail "location: 4th line, with /*...*/ comments" <<EOF
sx = b /* some
comment */
sy = d
)
EOF
expect <<EOF
sx = b
sy = d
FPVM, line 4: parse error near ')'
EOF

###############################################################################
