#!/bin/sh
. ./Common
. ./Patches

###############################################################################

#
# If we're going to spend the time to run under valgrind, make the most
# of it.
#

valgrind_orig=$VALGRIND
if [ "$VALGRIND" ]; then
	VALGRIND="$VALGRIND --leak-check=full --show-reachable=yes"
fi

PATCHDIR=../../../patches

do_test()
{
	ptest "patch: $n" -c -q <"$PATCHDIR/$n"
	expect </dev/null
}

forall_patches do_test

VALGRIND=$valgrind_orig

###############################################################################
