#!/bin/sh
. ./Common

###############################################################################

ptest "precedence: x = a+b*c+d" <<EOF
x = a+b*c+d
EOF
expect <<EOF
x = (+ (+ a (* b c)) d)
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = a+b/c+d" <<EOF
x = a+b/c+d
EOF
expect <<EOF
x = (+ (+ a (/ b c)) d)
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = a+b%c+d" <<EOF
x = a+b%c+d
EOF
expect <<EOF
x = (+ (+ a (% b c)) d)
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = a-b*c-d" <<EOF
x = a-b*c-d
EOF
expect <<EOF
x = (- (- a (* b c)) d)
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = a-b/c-d" <<EOF
x = a-b/c-d
EOF
expect <<EOF
x = (- (- a (/ b c)) d)
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = a-b%c-d" <<EOF
x = a-b%c-d
EOF
expect <<EOF
x = (- (- a (% b c)) d)
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = -a*b" <<EOF
x = -a*b
EOF
expect <<EOF
x = (* (! a) b)
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = a/b" <<EOF
x = -a/b
EOF
expect <<EOF
x = (/ (! a) b)
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = a%b" <<EOF
x = -a%b
EOF
expect <<EOF
x = (% (! a) b)
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = -sin(a)" <<EOF
x = -sin(a)
EOF
expect <<EOF
x = (! (sin a))
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = -max(a, b)" <<EOF
x = -max(a, b)
EOF
expect <<EOF
x = (! (max a b))
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = -if(a, b, c)" <<EOF
x = -if(a, b, c)
EOF
expect <<EOF
x = (! (if a b c))
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = -(a+b)" <<EOF
x = -(a+b)
EOF
expect <<EOF
x = (! (+ a b))
EOF

#------------------------------------------------------------------------------

ptest "precedence: x = a--b" <<EOF
x = a--b
EOF
expect <<EOF
x = (- a (! b))
EOF

###############################################################################
