#!/bin/sh
. ./Common

###############################################################################

ptest "precedence: sx = a+b*c+d" <<EOF
sx = a+b*c+d
EOF
expect <<EOF
sx = (+ (+ a (* b c)) d)
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = a+b/c+d" <<EOF
sx = a+b/c+d
EOF
expect <<EOF
sx = (+ (+ a (/ b c)) d)
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = a+b%c+d" <<EOF
sx = a+b%c+d
EOF
expect <<EOF
sx = (+ (+ a (% b c)) d)
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = a-b*c-d" <<EOF
sx = a-b*c-d
EOF
expect <<EOF
sx = (- (- a (* b c)) d)
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = a-b/c-d" <<EOF
sx = a-b/c-d
EOF
expect <<EOF
sx = (- (- a (/ b c)) d)
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = a-b%c-d" <<EOF
sx = a-b%c-d
EOF
expect <<EOF
sx = (- (- a (% b c)) d)
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = -a*b" <<EOF
sx = -a*b
EOF
expect <<EOF
sx = (* (- a) b)
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = a/b" <<EOF
sx = -a/b
EOF
expect <<EOF
sx = (/ (- a) b)
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = a%b" <<EOF
sx = -a%b
EOF
expect <<EOF
sx = (% (- a) b)
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = -sin(a)" <<EOF
sx = -sin(a)
EOF
expect <<EOF
sx = (- (sin a))
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = -max(a, b)" <<EOF
sx = -max(a, b)
EOF
expect <<EOF
sx = (- (max a b))
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = -if(a, b, c)" <<EOF
sx = -if(a, b, c)
EOF
expect <<EOF
sx = (- (if a b c))
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = -(a+b)" <<EOF
sx = -(a+b)
EOF
expect <<EOF
sx = (- (+ a b))
EOF

#------------------------------------------------------------------------------

ptest "precedence: sx = a--b" <<EOF
sx = a--b
EOF
expect <<EOF
sx = (- a (- b))
EOF

###############################################################################
