#!/bin/sh
. ./Common

# WORK IN PROGRESS

###############################################################################

ptest "prefix: per_frame=x = a+b" <<EOF
per_frame=x = a+b
EOF
expect <<EOF
per_frame = x = (+ a b)
EOF

#------------------------------------------------------------------------------

ptest "prefix: per_vertex= x = a+b" <<EOF
per_vertex = x = a+b
EOF
expect <<EOF
per_vertex = x = (+ a b)
EOF

#------------------------------------------------------------------------------

ptest "prefix: per_pixel=x = a+b" <<EOF
per_pixel=x = a+b
EOF
expect <<EOF
per_vertex = x = (+ a b)
EOF

###############################################################################
