#!/bin/sh
. ./Common

###############################################################################

ptest "relop: a == b" << EOF
sx = a == b
EOF
expect <<EOF
sx = (equal a b)
EOF

#------------------------------------------------------------------------------

ptest "relop: a < b" << EOF
sx = a < b
EOF
expect <<EOF
sx = (below a b)
EOF

#------------------------------------------------------------------------------

ptest "relop: a > b" << EOF
sx = a > b
EOF
expect <<EOF
sx = (above a b)
EOF

#------------------------------------------------------------------------------

ptest "relop: fold ==" << EOF
sx = 1 == 2
sy = 2 == 2
cx = 3 == 2
EOF
expect <<EOF
sx = 0
sy = 1
cx = 0
EOF

#------------------------------------------------------------------------------

ptest "relop: fold <" << EOF
sx = 1 < 2
sy = 2 < 2
cx = 3 < 2
EOF
expect <<EOF
sx = 1
sy = 0
cx = 0
EOF

#------------------------------------------------------------------------------

ptest "relop: fold >" << EOF
sx = 1 > 2
sy = 2 > 2
cx = 3 > 2
EOF
expect <<EOF
sx = 0
sy = 0
cx = 1
EOF

#------------------------------------------------------------------------------

ptest "relop: a == b ? c : d" << EOF
sx = a == b ? c : d
EOF
expect <<EOF
sx = (if (equal a b) c d)
EOF

#------------------------------------------------------------------------------

ptest "relop: a ? b : c == d" << EOF
sx = a ? b : c == d
EOF
expect <<EOF
sx = (if a b (equal c d))
EOF

#------------------------------------------------------------------------------

ptest "relop: a < b == c > d" << EOF
sx = a < b == c > d
EOF
expect <<EOF
sx = (equal (below a b) (above c d))
EOF

#------------------------------------------------------------------------------

ptest "relop: a+b < c-d" << EOF
sx = a+b < c-d
EOF
expect <<EOF
sx = (below (+ a b) (- c d))
EOF

#------------------------------------------------------------------------------

ptest "relop: a-b > c+d" << EOF
sx = a-b > c+d
EOF
expect <<EOF
sx = (above (- a b) (+ c d))
EOF

#------------------------------------------------------------------------------

ptest "relop: a != b" << EOF
sx = a != b
EOF
expect <<EOF
sx = (! (equal a b))
EOF

#------------------------------------------------------------------------------

ptest "relop: a <= b" << EOF
sx = a <= b
EOF
expect <<EOF
sx = (! (above a b))
EOF

#------------------------------------------------------------------------------

ptest "relop: a >= b" << EOF
sx = a >= b
EOF
expect <<EOF
sx = (! (below a b))
EOF

#------------------------------------------------------------------------------

ptest "relop: a < b != c >= d" << EOF
sx = a < b != c >= d
EOF
expect <<EOF
sx = (! (equal (below a b) (! (below c d))))
EOF

#------------------------------------------------------------------------------

ptest "relop: a+b <= c-d" << EOF
sx = a+b <= c-d
EOF
expect <<EOF
sx = (! (above (+ a b) (- c d)))
EOF

#------------------------------------------------------------------------------

ptest "relop: a-b >= c+d" << EOF
sx = a-b >= c+d
EOF
expect <<EOF
sx = (! (below (- a b) (+ c d)))
EOF

#------------------------------------------------------------------------------

ptest "relop: a != b ? c : d" << EOF
sx = a != b ? c : d
EOF
expect <<EOF
sx = (if (equal a b) d c)
EOF

#------------------------------------------------------------------------------

ptest "relop: a <= b ? c : d" << EOF
sx = a <= b ? c : d
EOF
expect <<EOF
sx = (if (above a b) d c)
EOF

#------------------------------------------------------------------------------

ptest "relop: a >= b ? c : d" << EOF
sx = a >= b ? c : d
EOF
expect <<EOF
sx = (if (below a b) d c)
EOF

#------------------------------------------------------------------------------

ptest "relop: 1 != 2 ? c : d" << EOF
sx = 1 != 2 ? c : d
EOF
expect <<EOF
sx = c
EOF

#------------------------------------------------------------------------------

ptest "relop: 2 != 2 ? c : d" << EOF
sx = 2 != 2 ? c : d
EOF
expect <<EOF
sx = d
EOF

###############################################################################
