#!/bin/sh
. ./Common

###############################################################################

ptest "stimuli, input, MIDI: fader -> range" -c -q \
    -v sx -m 0=63 -m 0=127 -m 0=0 <<EOF
midi "foo" { bar = fader(1, 0); }
sx = range(bar);
EOF
expect <<EOF
0.496063
1
0
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: fader -> unbounded" -c -q \
    -v sx -m 0=64 -m 0=127 -m 0=0 <<EOF
midi "foo" { bar = fader(1, 0); }
sx = unbounded(bar);
EOF
expect <<EOF
0.503937
1
0
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: fader -> cyclic" -c -q \
    -v sx -m 0=63 -m 0=127 -m 0=0 <<EOF
midi "foo" { bar = fader(1, 0); }
sx = cyclic(bar);
EOF
expect <<EOF
0.496063
1
0
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: fader -> button" -c -q \
    -v sx -m 0=63 -m 0=64 -m 0=127 -m 0=0 <<EOF
midi "foo" { bar = fader(1, 0); }
sx = button(bar);
EOF
expect <<EOF
0
1
1
0
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: fader -> switch" -c -q \
    -v sx -m 0=63 -m 0=64 -m 0=127 -m 0=0 <<EOF
midi "foo" { bar = fader(1, 0); }
sx = switch(bar);
EOF
expect <<EOF
0
1
1
0
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: differential -> range" -c -q \
    -v sx -m 0=127 -m 0=63 -m 0=0 -m 0=63 -m 0=63 -m 0=64 -m 0=66 -m 0=64 <<EOF
midi "foo" { bar = differential(1, 0); }
sx = range(bar);
EOF
expect <<EOF
0
0.496063
0.496063
0.992126
1
0.496063
0.00787402
0
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: differential -> unbounded" -c -q \
    -v sx -m 0=127 -m 0=63 -m 0=0 -m 0=63 -m 0=63 -m 0=64 -m 0=66 -m 0=64 <<EOF
midi "foo" { bar = differential(1, 0); }
sx = unbounded(bar);
EOF
expect <<EOF
-0.00787402
0.488189
0.488189
0.984252
1.48031
0.976378
0.488189
-0.015748
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: differential -> cyclic" -c -q \
    -v sx -m 0=127 -m 0=63 -m 0=0 -m 0=63 -m 0=63 -m 0=64 -m 0=66 -m 0=64 <<EOF
midi "foo" { bar = differential(1, 0); }
sx = cyclic(bar);
EOF
expect <<EOF
1
0.488189
0.488189
0.984252
0.472441
0.976378
0.488189
0.992126
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: differential -> button" -c -q \
    -v sx -m 0=127 -m 0=63 -m 0=0 -m 0=63 -m 0=63 -m 0=64 -m 0=0 -m 0=64 <<EOF
midi "foo" { bar = differential(1, 0); }
sx = button(bar);
EOF
expect <<EOF
0
1
1
1
1
0
0
0
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: button -> button" -c -q \
    -v sx -m 0=127 -m 0=0 -m 0=127 -m 0=0 <<EOF
midi "foo" { bar = button(1, 0); }
sx = button(bar);
EOF
expect <<EOF
1
0
1
0
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: button -> switch" -c -q \
    -v sx -m 0=127 -m 0=0 -m 0=127 -m 0=0 -m 0=127 <<EOF
midi "foo" { bar = button(1, 0); }
sx = switch(bar);
EOF
expect <<EOF
1
1
0
0
1
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: switch -> range" -c -q \
    -v sx -m 0=127 -m 0=0 -m 0=127 -m 0=0 <<EOF
midi "foo" { bar = switch(1, 0); }
sx = range(bar);
EOF
expect <<EOF
1
0
1
0
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: switch -> button" -c -q \
    -v sx -m 0=127 -m 0=0 -m 0=127 -m 0=0 <<EOF
midi "foo" { bar = switch(1, 0); }
sx = button(bar);
EOF
expect <<EOF
1
0
1
0
EOF

#------------------------------------------------------------------------------

ptest "stimuli, input, MIDI: test -Wundefined" -c -q -Wundefined <<EOF
midi "foo" { bar = switch(1, 0); }
foo = button(bar);
per_frame:
	sx = foo;
EOF
expect <<EOF
EOF

###############################################################################
