#!/bin/sh
. ./Common

###############################################################################

ptest "stimuli: range(1, 0)" -c -q << EOF
midi "foo" {
	bar = range(1, 0);
}
EOF
expect <<EOF
EOF

#------------------------------------------------------------------------------

ptest "stimuli: range(16, 127)" -c -q << EOF
midi "foo" {
	bar = range(16, 127)
}
EOF
expect <<EOF
EOF

#------------------------------------------------------------------------------

ptest_fail "stimuli: range(17, 0)" -c -q << EOF
midi "foo" {
	bar = range(17, 0);
}
EOF
expect <<EOF
line 2: MIDI channel must be within 1-16 near ');'
EOF

#------------------------------------------------------------------------------

ptest_fail "stimuli: range(1, 128)" -c -q << EOF
midi "foo" {
	bar = range(1, 128);
}
EOF
expect <<EOF
line 2: MIDI controller must be within 0-127 near ');'
EOF

#------------------------------------------------------------------------------

ptest_fail "stimuli: range(0, 0)" -c -q << EOF
midi "foo" {
	bar = range(0, 0);
}
EOF
expect <<EOF
line 2: MIDI channel must be within 1-16 near ');'
EOF

#------------------------------------------------------------------------------

ptest_fail "stimuli: range(1, -1)" -c -q << EOF
midi "foo" {
	bar = range(1, -1);
}
EOF
expect <<EOF
line 2: MIDI controller must be within 0-127 near ');'
EOF

#------------------------------------------------------------------------------

ptest "stimuli: differential(1, 0)" -c -q << EOF
midi "foo" {
	bar = differential(1, 0);
}
EOF
expect <<EOF
EOF

#------------------------------------------------------------------------------

ptest "stimuli: button(1, 0)" -c -q << EOF
midi "foo" {
	bar = button(1, 0);
}
EOF
expect <<EOF
EOF

#------------------------------------------------------------------------------

ptest "stimuli: toggle(1, 0)" -c -q << EOF
midi "foo" {
	bar = toggle(1, 0);
}
EOF
expect <<EOF
EOF

#------------------------------------------------------------------------------

ptest "stimuli: range(0) (wildcard)" -c -q << EOF
midi "foo" {
	bar = range(0);
}
EOF
expect <<EOF
EOF

###############################################################################
