#!/bin/sh
. ./Common

###############################################################################

ptest "wrap: baseline" <<EOF
sx = b + c
EOF
expect <<EOF
sx = (+ b c)
EOF

#------------------------------------------------------------------------------

ptest "wrap: with newline" <<EOF
sx = b +
c
EOF
expect <<EOF
sx = (+ b c)
EOF

#------------------------------------------------------------------------------

ptest "wrap: two assignments on two lines" <<EOF
sx = b + c
sy = e + f
EOF
expect <<EOF
sx = (+ b c)
sy = (+ e f)
EOF

#------------------------------------------------------------------------------

ptest "wrap: two assignments on one line" <<EOF
sx = b + c  sy = e + f
EOF
expect <<EOF
sx = (+ b c)
sy = (+ e f)
EOF

#------------------------------------------------------------------------------

ptest "wrap: one assignment ending with semicolon" <<EOF
sx = b + c;
EOF
expect <<EOF
sx = (+ b c)
EOF

#------------------------------------------------------------------------------

ptest "wrap: one assignment ending with multiple semicolons" <<EOF
sx = b + c;;;;;;;;;;;
EOF
expect <<EOF
sx = (+ b c)
EOF

#------------------------------------------------------------------------------

ptest "wrap: two assignments separated by semicolon" <<EOF
sx = b + c; sy = e + f
EOF
expect <<EOF
sx = (+ b c)
sy = (+ e f)
EOF

#------------------------------------------------------------------------------

ptest_fail "wrap: one assignment containing semicolon (1)" <<EOF
sx = b +; c
EOF
expect <<EOF
FPVM, line 1: parse error near ';'
EOF

#------------------------------------------------------------------------------

ptest_fail "wrap: one assignment containing semicolon (2)" <<EOF
sx = b; + c
EOF
expect <<EOF
sx = b
FPVM, line 1: parse error near '+'
EOF

###############################################################################
