#!/bin/sh
. ./Common

###############################################################################

ptest "-Wundefined: variable defined globally" -q -Wundefined <<EOF
foo = 0
per_frame:
	bar = foo
per_vertex:
	bar = foo
EOF
expect <<EOF
EOF

#------------------------------------------------------------------------------

ptest "-Wundefined: variable defined per-frame" -q -Wundefined <<EOF
per_frame:
	foo = 1
	bar = foo
per_vertex:
	bar = foo
EOF
expect <<EOF
EOF

#------------------------------------------------------------------------------

ptest "-Wundefined: variable defined per-vertex" -q -Wundefined <<EOF
per_vertex:
	foo = 1
	bar = foo
EOF
expect <<EOF
EOF

#------------------------------------------------------------------------------

ptest "-Wundefined: variable undefined in per-frame" -q -Wundefined <<EOF
per_frame:
	bar = foo
EOF
expect <<EOF
reading undefined variable foo
EOF

#------------------------------------------------------------------------------

ptest "-Wundefined: variable undefined in per-vertex" -q -Wundefined <<EOF
per_vertex:
	bar = foo
EOF
expect <<EOF
reading undefined variable foo
EOF

#------------------------------------------------------------------------------

ptest "-Wundefined: old-style read-modify-write" -q -Wundefined <<EOF
per_vertex =
	foo = foo
EOF
expect <<EOF
EOF

#------------------------------------------------------------------------------

ptest "-Wundefined: old-style undefined" -q -Wundefined <<EOF
per_vertex =
	foo = bar
EOF
expect <<EOF
variable bar is only read, never set
EOF

###############################################################################
