\newcommand{\figarch}{
\begin{figure}[!tb]
\begin{center}
\includegraphics{arch.pdf}
\end{center}
\caption{Input event processing in Flickernoise.}
\label{arch}
\end{figure}}

\newcommand{\figmsg}{
\begin{figure}[!tb]
\begin{center}
\includegraphics{msg.pdf}
\end{center}
\caption{Anatomy of a MIDI Control Change message.}
\label{msg}
\end{figure}}

\newcommand{\figbind}{
\begin{figure}[!tb]
\begin{center}
\includegraphics{bind.pdf}
\end{center}
\caption{When binding a control variable, information from the device
  database, a translation map, and the table of patch variables is
  combined into a stimulus entry.}
\label{bind}
\end{figure}}

\newcommand{\figstim}{
\begin{figure}[!tb]
\begin{center}
\includegraphics{stim.pdf}
\end{center}
\caption{When a MIDI control message is received, Flickernoise looks
  for a matching stimulus and processes the value accordingly.}
\label{stim}
\end{figure}}
