#!/bin/sh -e
#
# mknocvars - Generate the list of variables forbidden as control variables
#
# Copyright 2012 by Werner Almesberger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#

sed 's/#.*//;/^ *$/d' $1 | LANG=C sort | {
	while read n; do
		echo "$n" | grep SF_LIVE >/dev/null || continue
		set - $n
		echo $1 | sed 's/[0-9]$/{\\em n}/'
	done
} | uniq | sed 's/_/\\_/g;s/.*/{\\tt &},/' | sed '${s/,$/./;s/^/and /;}'
